version: "3"
services:
    nav-postgres:
        image: postgres:latest
        container_name: nav-postgres
        restart: always
        expose:
            - 5432
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=nav
            
    nav:
        image: nav:latest
        build:
            context: .
            dockerfile: Dockerfile-nav

        container_name: nav
        expose:
            - 8080
        ports:
            - 8080:8080
        depends_on:
            - nav-postgres
            
        links:
            - nav-postgres
           
        environment:
            - DB_URL=jdbc:postgresql://nav-postgres:5432/nav
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres